### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by tjaensch** [jaytaylor/html2text#26] opened 2018-02-22 19:24 UTC
It's producing the following errors:

./test.go:6:2: imported and not used: "github.com/jaytaylor/html2text"
./test.go:50:15: undefined: FromString
./test.go:50:37: undefined: Options

This is the code from your README example:

package main

import (
	"fmt"

	"github.com/jaytaylor/html2text"
)

func main() {
	inputHTML := `
<html>
  <head>
    <title>My Mega Service</title>
    <link rel=\"stylesheet\" href=\"main.css\">
    <style type=\"text/css\">body { color: #fff; }</style>
  </head>

  <body>
    <div class="logo">
      <a href="http://jaytaylor.com/"><img src="/logo-image.jpg" alt="Mega Service"/></a>
    </div>

    <h1>Welcome to your new account on my service!</h1>

    <p>
      Here is some more information:

      <ul>
        <li>Link 1: <a href="https://example.com">Example.com</a></li>
        <li>Link 2: <a href="https://example2.com">Example2.com</a></li>
        <li>Something else</li>
      </ul>
    </p>

    <table>
      <thead>
        <tr><th>Header 1</th><th>Header 2</th></tr>
      </thead>
      <tfoot>
        <tr><td>Footer 1</td><td>Footer 2</td></tr>
      </tfoot>
      <tbody>
        <tr><td>Row 1 Col 1</td><td>Row 1 Col 2</td></tr>
        <tr><td>Row 2 Col 1</td><td>Row 2 Col 2</td></tr>
      </tbody>
    </table>
  </body>
</html>`

	text, err := FromString(inputHTML, Options{PrettyTables: true})
	if err != nil {
		panic(err)
	}
	fmt.Println(text)
}

**Comment by jaytaylor** [comment] 2018-02-22 21:40
Hi @tjaensch, thanks for letting me know about this.  The package named was missing from the `FromString` and `Options` references (e.g. should be `html2text.FromString`, and `html2text.Options`).

I just merged the fix #27 

Thanks again, take care.  Please close this if you agree the problem is solved.

**Closed** 2018-02-22 21:44 UTC
