### ISSUE TITLE
Removes all newlines in HTML doc

### ISSUE THREAD

**Issue by theanine** [jaytaylor/html2text#22] opened 2017-09-22 08:06 UTC
Example:
```
<html><head></head><body><pre>foo1
bar1

foo2
bar2

foo3
bar3

foo4
bar4

foo5
bar5

foo6
bar6

</pre>
</body></html>
```

Results in:
```
foo1 bar1 foo2 bar2 foo3 bar3 foo4 bar4 foo5 bar5 foo6 bar6
```

**Comment by jaytaylor** [comment] 2017-09-22 17:22
They @theanine, thanks for pointing this out.

A PR which corrects the behavior is certainly welcome!

**Comment by helb** [comment] 2017-12-14 14:16
Probably a duplicate of #6 

There's a patch from @Kleissner waiting in a comment, i'll add a test case and make a PR of it.

**Comment by jaytaylor** [comment] 2017-12-14 17:47
Fantastic @helb, looking forward to it.

**Comment by helb** [comment] 2017-12-14 19:46
@jaytaylor ^^ here it is, please review the changes (tests pass, but i have little to no experience with Go…)

**Closed** 2017-12-14 22:17 UTC
