### ISSUE TITLE
Pretty Tables: large tables break down (unfortunately) with index out of range...

### ISSUE THREAD

**Issue by GwynethLlewelyn** [jaytaylor/html2text#20] opened 2017-08-07 11:34 UTC
I'm _really_ loving your html2text functionality, especially because you turn some HTML features into quasi-Markdown text, which is more than awesome, it's close to perfection! Thank you very much!

I have an application which attempts to write HTML logs to a WebSocket, but, when it fails to do so, it prints the logs out to the console, which, of course, looks awful for a human to read! I'm already using ANSI colour escapes to at least give some idea of what is urgent and what is not, but clearly a more legible output was necessary... and your package does exactly that, thank you!

Unfortunately, with very large tables, it seems to fail with:

```panic: runtime error: index out of range

goroutine 23 [running]:
github.com/olekukonko/tablewriter.(*Table).printHeading(0xc4200126c0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/olekukonko/tablewriter/table.go:333 +0x47d
github.com/olekukonko/tablewriter.(*Table).Render(0xc4200126c0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/olekukonko/tablewriter/table.go:112 +0x3a
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleTableElement(0xc4201fc0f0, 0xc42018b3b0, 0x1, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:270 +0x5f9
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc4201fc0f0, 0xc42018b3b0, 0xc4201d0160, 0xc420178000)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:217 +0x6ed
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc4201fc0f0, 0xc42018b3b0, 0x7, 0x444868)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc4201fc0f0, 0xc42018b340, 0xa, 0xc4201f7098)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc4201fc0f0, 0xc42018b340, 0xc4201a7a70, 0x81)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:160 +0x76a
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc4201fc0f0, 0xc42018b340, 0x68, 0x444868)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc4201fc0f0, 0xc42018b2d0, 0xc4201f74ac, 0x1)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc4201fc0f0, 0xc42018b2d0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc4201fc0f0, 0xc42018b2d0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc4201fc0f0, 0xc42018b1f0, 0xc4201f78c0, 0x45d9c4)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc4201fc0f0, 0xc42018b1f0, 0x932bc0, 0x1)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc4201fc0f0, 0xc42018b1f0, 0x7f1edd570000, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc4201fc0f0, 0xc42018b180, 0x410e58, 0xf0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc4201fc0f0, 0xc42018b180, 0x0, 0x402c7e)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:318 +0x77
github.com/jaytaylor/html2text.FromHTMLNode(0xc42018b180, 0xc4201f7f1d, 0x1, 0x1, 0x0, 0x0, 0xc001, 0xc420200000)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:32 +0xe8
github.com/jaytaylor/html2text.FromReader(0xba2ea0, 0xc420200000, 0xc4201f7f1d, 0x1, 0x1, 0xc000, 0x0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:53 +0xce
github.com/jaytaylor/html2text.FromString(0xc42061e000, 0xa046, 0xc4201f7f1d, 0x1, 0x1, 0x2, 0x0, 0xc4201f80b8, 0x4681d9)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:59 +0x12c
```

I'm assuming that the problem is mostly with [tablewriter](https://github.com/olekukonko/tablewriter/), and not with your package? My tables have some 50 rows and a dozen columns or so. I have not tried with smaller tables (there aren't any!).

**Comment by jaytaylor** [comment] 2017-08-07 16:57
Hi @GwynethLlewelyn ,

Happy to hear you're liking it, and sorry to hear it's breaking on large tables.  It's hard to say offhand what the source of the issue is.

The ideal scenario is if you're able to provide a raw input and exact steps to reproduce the breakage.  Shoot it over and I'll be happy to take a look.

Best,
Jay

**Comment by GwynethLlewelyn** [comment] 2017-08-08 11:27
Good idea! Of course this won't run on the Go Playground, but at least you can try to run it locally on your own Go environment: https://play.golang.org/p/6jsINa5Bq_

**Comment by jaytaylor** [comment] 2017-08-08 15:47
I'm getting a page with only the text "Snippet not found".

**Comment by GwynethLlewelyn** [comment] 2017-08-13 22:25
Oh dang. I thought those snippets would stay around for longer. Here goes a [gist](https://gist.github.com/GwynethLlewelyn/85e4f1e97243789f983489200a807e65#file-html2text-largetable-test-go) instead. I've tried both under Mac OS X (Version 10.12.6 (16G29), Darwin Kernel Version 16.7.0) and Ubuntu Linux 16.04.3 LTS (Kernel 4.4.0-91-generic); both are running `go` version 1.8.3.

Output as follows (on Mac OS X):
```panic: runtime error: index out of range

goroutine 1 [running]:
github.com/olekukonko/tablewriter.(*Table).printHeading(0xc42008c6c0)
	/Users/gwyneth/go/src/github.com/olekukonko/tablewriter/table.go:333 +0x47d
github.com/olekukonko/tablewriter.(*Table).Render(0xc42008c6c0)
	/Users/gwyneth/go/src/github.com/olekukonko/tablewriter/table.go:112 +0x3a
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleTableElement(0xc420178000, 0xc4200ca3f0, 0x0, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:270 +0x5f9
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc420178000, 0xc4200ca3f0, 0x0, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:217 +0x6ed
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc420178000, 0xc4200ca3f0, 0xc420016510, 0x10000000000000d)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc420178000, 0xc4200ca380, 0x3, 0x7)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc420178000, 0xc4200ca380, 0x100dab2, 0xc420086640)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:160 +0x76a
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc420178000, 0xc4200ca380, 0xc420086640, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc420178000, 0xc4200ca310, 0xc420014190, 0xc42001a000)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc420178000, 0xc4200ca310, 0x0, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc420178000, 0xc4200ca310, 0x0, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc420178000, 0xc4200ca230, 0x70, 0x1)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc420178000, 0xc4200ca230, 0x1106e00, 0xc4200e9301)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc420178000, 0xc4200ca230, 0x11fd000, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc420178000, 0xc4200ca1c0, 0x100e308, 0xf0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc420178000, 0xc4200ca1c0, 0x0, 0x1001d2e)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:318 +0x77
github.com/jaytaylor/html2text.FromHTMLNode(0xc4200ca1c0, 0xc420039f37, 0x1, 0x1, 0x0, 0x0, 0xa001, 0xc420016810)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:32 +0xe8
github.com/jaytaylor/html2text.FromReader(0x11a22e0, 0xc420016810, 0xc420039f37, 0x1, 0x1, 0xa000, 0xc42000c018, 0xc420039f68, 0x1)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:53 +0xce
github.com/jaytaylor/html2text.FromString(0x112018c, 0x933a, 0xc420039f37, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/gwyneth/go/src/github.com/jaytaylor/html2text/html2text.go:59 +0x12c
main.main()
	/Users/gwyneth/go/src/hello/hello.go:62 +0xf8
```
On Linux (sorry, the filenames and directory structure is not the same, but the trace is pretty much the same one for both OSes):

```panic: runtime error: index out of range

goroutine 1 [running]:
github.com/olekukonko/tablewriter.(*Table).printHeading(0xc4200886c0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/olekukonko/tablewriter/table.go:333 +0x47d
github.com/olekukonko/tablewriter.(*Table).Render(0xc4200886c0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/olekukonko/tablewriter/table.go:112 +0x3a
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleTableElement(0xc42016e000, 0xc4200d0380, 0x40dc12, 0xc420084780)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:270 +0x5f9
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc42016e000, 0xc4200d0380, 0xc420037090, 0x48f73d)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:217 +0x6ed
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc42016e000, 0xc4200d0380, 0xc420062310, 0x78)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc42016e000, 0xc4200d0310, 0x48eeba, 0x10)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc42016e000, 0xc4200d0310, 0x4f6dc0, 0x8)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:160 +0x76a
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc42016e000, 0xc4200d0310, 0x7f1ce9dbe4b0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc42016e000, 0xc4200d02a0, 0x438b60, 0xc4200806e0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc42016e000, 0xc4200d02a0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc42016e000, 0xc4200d02a0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc42016e000, 0xc4200d01c0, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).handleElement(0xc42016e000, 0xc4200d01c0, 0x4fb380, 0xc4200df501)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:228 +0x48b
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc42016e000, 0xc4200d01c0, 0x7f1ce9dbe4b0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:325 +0x46
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverseChildren(0xc42016e000, 0xc4200d0150, 0x40e468, 0xf0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:331 +0x47
github.com/jaytaylor/html2text.(*textifyTraverseContext).traverse(0xc42016e000, 0xc4200d0150, 0x0, 0x401cee)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:318 +0x77
github.com/jaytaylor/html2text.FromHTMLNode(0xc4200d0150, 0xc420037f57, 0x1, 0x1, 0x0, 0x0, 0xa001, 0xc420068720)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:32 +0xe8
github.com/jaytaylor/html2text.FromReader(0x592300, 0xc420068720, 0xc420037f57, 0x1, 0x1, 0xa000, 0x5, 0xc420080780, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:53 +0xce
github.com/jaytaylor/html2text.FromString(0x5140ab, 0x95bf, 0xc420037f57, 0x1, 0x1, 0x509ac9, 0x7, 0x0, 0x0)
	/var/www/clients/client6/web61/home/bot/go/src/github.com/jaytaylor/html2text/html2text.go:59 +0x12c
main.main()
	/var/www/clients/client6/web61/home/bot/go/src/html2text-test/html2text-test.go:61 +0x66
```

**Comment by jaytaylor** [comment] 2017-08-16 17:48
Hey @GwynethLlewelyn , thanks for posting the gist.  I've reproduced the issue and am looking into it now.

Best,
Jay

**Comment by GwynethLlewelyn** [comment] 2017-08-16 22:03
Thanks, @jaytaylor :) I can imagine the problem is not with html2text but with the library you include... but let's see what you can find out...

**Comment by jaytaylor** [comment] 2017-08-16 22:56
It appears that the tablewriter library doesn't tolerate the case of fewer table header columns than data columns.

I've submitted a PR with a fix at https://github.com/olekukonko/tablewriter/pull/68 , we'll see if we can get some traction.  If it doesn't get resolved in a timely fashion I'll just switch html2text to reference my fork.

Cheers,
Jay

**Comment by olekukonko** [comment] 2017-09-08 15:19
@jaytaylor your PR has been merged.

**Comment by jaytaylor** [comment] 2017-09-18 15:55
@olekukonko Thanks!

@GwynethLlewelyn I'm marking this one as resolved.  If you feel otherwise just re-open or open another issue.

Best,
Jay

**Closed by jaytaylor** 2017-09-18 15:55 UTC

**Comment by GwynethLlewelyn** [comment] 2017-09-19 10:01
Perfect! I can confirm that this works flawlessly now. Thank you so much! I didn't even notice the issue of having fewer table header columns than data columns — but nevermind that, it just made `html2text` even better, handling one more edge case! 👍
